-- Seed bảng Mã màu phôi (podColors) từ 154 màu trong file "Giá Sản Phẩm Teement"
-- Mã hex theo bảng màu Gildan / Comfort Colors (gần đúng — chỉnh lại trong tab Mã màu phôi nếu cần)
-- Chạy lại an toàn: màu đã có (trùng id) sẽ được bỏ qua.

create table if not exists "podColors" (
  id text primary key,
  name text not null,
  hex text not null default '#ffffff',
  created text
);
alter table "podColors" disable row level security;

insert into "podColors" (id, name, hex, created) values
('color-antique-cherry-red', 'Antique Cherry Red', '#971B2F', now()::text),
('color-antique-irish-green', 'Antique Irish Green', '#00843D', now()::text),
('color-antique-jade-dome', 'Antique Jade Dome', '#006269', now()::text),
('color-antique-orange', 'Antique Orange', '#B5532E', now()::text),
('color-antique-sapphire', 'Antique Sapphire', '#006A8E', now()::text),
('color-aquatic', 'Aquatic', '#4AB5C4', now()::text),
('color-ash', 'Ash', '#C8C9C7', now()::text),
('color-azalea', 'Azalea', '#DD74A1', now()::text),
('color-banana', 'Banana', '#F8E08E', now()::text),
('color-bay', 'Bay', '#7BA8A6', now()::text),
('color-berry', 'Berry', '#8E4585', now()::text),
('color-black', 'Black', '#25282A', now()::text),
('color-blackberry', 'Blackberry', '#52466E', now()::text),
('color-blossom', 'Blossom', '#F2C4CE', now()::text),
('color-blue-dusk', 'Blue Dusk', '#3A4358', now()::text),
('color-blue-jean', 'Blue Jean', '#5A7E92', now()::text),
('color-blue-spruce', 'Blue Spruce', '#466A5E', now()::text),
('color-boysenberry', 'Boysenberry', '#6E4066', now()::text),
('color-brick', 'Brick', '#9A3B26', now()::text),
('color-bright-orange', 'Bright Orange', '#FF7F32', now()::text),
('color-bright-salmon', 'Bright Salmon', '#FF8D6D', now()::text),
('color-brown', 'Brown', '#5B4636', now()::text),
('color-brown-savanna', 'Brown Savanna', '#7A6855', now()::text),
('color-burnt-orange', 'Burnt Orange', '#C25A26', now()::text),
('color-butter', 'Butter', '#F6E3B4', now()::text),
('color-cardinal', 'Cardinal', '#8A1538', now()::text),
('color-cardinal-red', 'Cardinal Red', '#9D2235', now()::text),
('color-caribe', 'Caribe', '#33BFB8', now()::text),
('color-carolina-blue', 'Carolina Blue', '#7BA4DB', now()::text),
('color-chalky-mint', 'Chalky Mint', '#8FD6BD', now()::text),
('color-chambray', 'Chambray', '#BDD6E6', now()::text),
('color-charcoal', 'Charcoal', '#66676C', now()::text),
('color-cherry-red', 'Cherry Red', '#AC2B37', now()::text),
('color-chili', 'Chili', '#9B3E32', now()::text),
('color-china-blue', 'China Blue', '#5C7398', now()::text),
('color-citrus', 'Citrus', '#E8E337', now()::text),
('color-cobalt', 'Cobalt', '#0057B8', now()::text),
('color-coral-silk', 'Coral Silk', '#F27C66', now()::text),
('color-cornsilk', 'Cornsilk', '#F2E6A7', now()::text),
('color-crimson', 'Crimson', '#862633', now()::text),
('color-crunchberry', 'Crunchberry', '#E15D8C', now()::text),
('color-daisy', 'Daisy', '#FED141', now()::text),
('color-dark-chocolate', 'Dark Chocolate', '#382F2D', now()::text),
('color-dark-green', 'Dark Green', '#234F33', now()::text),
('color-dark-heather', 'Dark Heather', '#425563', now()::text),
('color-denim', 'Denim', '#46647E', now()::text),
('color-dusty-rose', 'Dusty Rose', '#DCA9A0', now()::text),
('color-electric-green', 'Electric Green', '#4DBD38', now()::text),
('color-emerald', 'Emerald', '#007A53', now()::text),
('color-espresso', 'Espresso', '#4A3C31', now()::text),
('color-flo-blue', 'Flo Blue', '#5576A7', now()::text),
('color-forest', 'Forest', '#1E4620', now()::text),
('color-forest-green', 'Forest Green', '#24503F', now()::text),
('color-garnet', 'Garnet', '#7D2935', now()::text),
('color-gold', 'Gold', '#EAAA00', now()::text),
('color-granite', 'Granite', '#7D7F81', now()::text),
('color-grape', 'Grape', '#6E2C6B', now()::text),
('color-graphite', 'Graphite', '#4B4F54', now()::text),
('color-graphite-heather', 'Graphite Heather', '#707372', now()::text),
('color-grass', 'Grass', '#4A8B2C', now()::text),
('color-gravel', 'Gravel', '#888B8D', now()::text),
('color-grey', 'Grey', '#919294', now()::text),
('color-heather-dark-green', 'Heather Dark Green', '#3D5B4C', now()::text),
('color-heather-dark-maroon', 'Heather Dark Maroon', '#6D3332', now()::text),
('color-heather-dark-navy', 'Heather Dark Navy', '#33415C', now()::text),
('color-heather-deep-royal', 'Heather Deep Royal', '#35528C', now()::text),
('color-heather-military-green', 'Heather Military Green', '#6B6B4B', now()::text),
('color-heather-navy', 'Heather Navy', '#3A4664', now()::text),
('color-heather-radiant-orchid', 'Heather Radiant Orchid', '#A15A95', now()::text),
('color-heather-red', 'Heather Red', '#BF4D57', now()::text),
('color-heather-sapphire', 'Heather Sapphire', '#2D7BA8', now()::text),
('color-heather-scarlet-red', 'Heather Scarlet Red', '#C25B63', now()::text),
('color-heliconia', 'Heliconia', '#DB3E79', now()::text),
('color-hemp', 'Hemp', '#7F8A70', now()::text),
('color-hydrangea', 'Hydrangea', '#9BB8D3', now()::text),
('color-ice-blue', 'Ice Blue', '#A5C8DE', now()::text),
('color-ice-grey', 'Ice Grey', '#D7D2CB', now()::text),
('color-indigo-blue', 'Indigo Blue', '#486D87', now()::text),
('color-irish-green', 'Irish Green', '#00A74A', now()::text),
('color-island-green', 'Island Green', '#2BB673', now()::text),
('color-island-reef', 'Island Reef', '#A0E5CE', now()::text),
('color-ivory', 'Ivory', '#F1E6D2', now()::text),
('color-khaki', 'Khaki', '#BBA98C', now()::text),
('color-kiwi', 'Kiwi', '#8EBF3F', now()::text),
('color-lagoon', 'Lagoon', '#48A9C5', now()::text),
('color-light-blue', 'Light Blue', '#A3C7E8', now()::text),
('color-light-green', 'Light Green', '#A1D2A0', now()::text),
('color-light-pink', 'Light Pink', '#F2C4D0', now()::text),
('color-lilac', 'Lilac', '#BCA8D0', now()::text),
('color-lime', 'Lime', '#92BF55', now()::text),
('color-maroon', 'Maroon', '#6E1F2E', now()::text),
('color-melon', 'Melon', '#FFA38B', now()::text),
('color-midnight', 'Midnight', '#232C43', now()::text),
('color-military-green', 'Military Green', '#5F614E', now()::text),
('color-mineral-black', 'Mineral Black', '#3A3A38', now()::text),
('color-mineral-grey', 'Mineral Grey', '#ACACA7', now()::text),
('color-mineral-navy', 'Mineral Navy', '#3A4256', now()::text),
('color-mineral-purple', 'Mineral Purple', '#6B5876', now()::text),
('color-mineral-silver', 'Mineral Silver', '#C7C7C1', now()::text),
('color-mint-green', 'Mint Green', '#A0CFAB', now()::text),
('color-moss', 'Moss', '#737B4C', now()::text),
('color-mustard', 'Mustard', '#DEA82C', now()::text),
('color-mystic-blue', 'Mystic Blue', '#7FA8C9', now()::text),
('color-natural', 'Natural', '#EDE6D6', now()::text),
('color-navy', 'Navy', '#263147', now()::text),
('color-neon-blue', 'Neon Blue', '#2DA8FF', now()::text),
('color-neon-cantaloupe', 'Neon Cantaloupe', '#FFB673', now()::text),
('color-neon-green', 'Neon Green', '#52E252', now()::text),
('color-neon-lemon', 'Neon Lemon', '#EFF54B', now()::text),
('color-neon-pink', 'Neon Pink', '#FF5FA2', now()::text),
('color-neon-red-orange', 'Neon Red Orange', '#FF5A3C', now()::text),
('color-neon-violet', 'Neon Violet', '#A05EEA', now()::text),
('color-off-white', 'Off White', '#F1ECE1', now()::text),
('color-old-gold', 'Old Gold', '#CBA052', now()::text),
('color-orange', 'Orange', '#F4633A', now()::text),
('color-orchid', 'Orchid', '#C7A4D8', now()::text),
('color-paprika', 'Paprika', '#B0523B', now()::text),
('color-peachy', 'Peachy', '#FCB29A', now()::text),
('color-pepper', 'Pepper', '#635E5B', now()::text),
('color-periwinkle', 'Periwinkle', '#8393CA', now()::text),
('color-purple', 'Purple', '#4F2D7F', now()::text),
('color-red', 'Red', '#D50032', now()::text),
('color-royal', 'Royal', '#1D4F91', now()::text),
('color-royal-caribe', 'Royal Caribe', '#2F8DC1', now()::text),
('color-russet', 'Russet', '#74452F', now()::text),
('color-solid-navy-blend', 'SOLID NAVY BLEND', '#2C3A55', now()::text),
('color-solid-pink-blend', 'SOLID PINK BLEND', '#F0A8C0', now()::text),
('color-solid-red-blend', 'SOLID RED BLEND', '#C43A45', now()::text),
('color-solid-vintage-navy-blend', 'SOLID VINTAGE NAVY BLEND', '#38495E', now()::text),
('color-solid-white-blend', 'SOLID WHITE BLEND', '#F2F2F0', now()::text),
('color-safety-green', 'Safety Green', '#C6D219', now()::text),
('color-safety-orange', 'Safety Orange', '#FF6A13', now()::text),
('color-safety-pink', 'Safety Pink', '#FF7BAC', now()::text),
('color-sage', 'Sage', '#AEB599', now()::text),
('color-sand', 'Sand', '#DCD0BA', now()::text),
('color-sandstone', 'Sandstone', '#D5C4A9', now()::text),
('color-sapphire', 'Sapphire', '#0077C8', now()::text),
('color-seafoam', 'Seafoam', '#A0E5C8', now()::text),
('color-sky', 'Sky', '#8FCAE7', now()::text),
('color-sport-grey', 'Sport Grey', '#B2B4B3', now()::text),
('color-sunset', 'Sunset', '#F2705F', now()::text),
('color-tangerine', 'Tangerine', '#FF8A3D', now()::text),
('color-tennessee-orange', 'Tennessee Orange', '#FF8200', now()::text),
('color-terracotta', 'Terracotta', '#BC6A45', now()::text),
('color-texas-orange', 'Texas Orange', '#BF5700', now()::text),
('color-topaz-blue', 'Topaz Blue', '#2FA8C5', now()::text),
('color-tropical-blue', 'Tropical Blue', '#00A9CE', now()::text),
('color-true-navy', 'True Navy', '#2E4265', now()::text),
('color-turf-green', 'Turf Green', '#348338', now()::text),
('color-tweed', 'Tweed', '#7C7F72', now()::text),
('color-vineyard', 'Vineyard', '#674662', now()::text),
('color-violet', 'Violet', '#8A7BB8', now()::text),
('color-washed-denim', 'Washed Denim', '#7E97AF', now()::text),
('color-watermelon', 'Watermelon', '#FC6C85', now()::text),
('color-white', 'White', '#FFFFFF', now()::text),
('color-wine', 'Wine', '#722F37', now()::text),
('color-yam', 'Yam', '#C06636', now()::text),
('color-yellow-haze', 'Yellow Haze', '#F3DE8A', now()::text)
on conflict (id) do nothing;

select count(*) as "tổng số màu" from "podColors";
